language: cpp
branches:
  only:
    - master
rvm:
  - 1.9.3
compiler:
  - gcc
  - clang
script:
  - cd src && rake install
  - cd test && make && sudo ./cgroup_unit_test && sudo ./fs_unit_test && ./strconv_unit_test

