language: cpp
branches:
  only:
    - master
rvm:
  - 1.9.3
compiler:
  - gcc
  - clang
script:
  - pushd src && rake install && popd
  - pushd test && make && sudo ./fs_unit_test && ./strconv_unit_test && popd
  - /usr/local/bin/lrun --version
  - '! /usr/local/bin/lrun true'
