language: cpp
branches:
  only:
    - master
rvm:
  - 1.9.3
compiler:
  - gcc
  - clang
env:
  - NODEBUG=1
  - ''
script:
  - pushd src && rake install && popd
  - ls -l src/lrun /usr/local/sbin/lrun
  
